### ISSUE TITLE
帮我看看这些代码吧

### ISSUE THREAD

**Issue by ice1000** [ice1000/OI-codes#1]
http://codevs.cn/problem/3261/
http://codevs.cn/problem/1001/
http://codevs.cn/problem/1031/
强势 @0x00-pl

**Comment by 0x00-pl** [comment]
第一题是语文题，看不懂
第二题搜索一下 每个点存最大最小值
第三题大概打个34以下所有质数的表然后暴力搜就可以吧

**Comment by ice1000** [comment]
@0x00-pl 我代码写的有，思路和你差不多，在OI-codes里面有的 :yum:

**Comment by ice1000** [comment]
帮我看看代码呗 :+1:

**Comment by ice1000** [comment]
@0x00-pl 喂

**Comment by 0x00-pl** [comment]
这两天回家啦～ 
第一个那个我超时了 搞不懂
后面的没做

**Comment by ice1000** [comment]
@0x00-pl 我也是超时啊！！！ :sob: 
我还没回家呢 现在在学校 :sob:
